version: '3.8'

services:
  hubspot_integration:
    build: .
    container_name: hubspot_integration
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: default
    restart: unless-stopped
